In [1]:
import numpy as np

In [2]:
#NumPy's main datatype is ndarray i.e. n-dimensional array
a1=np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
a2=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
a3=np.array([[[1,2,3],[4,5,6]],[[11,12,13],[14,15,16]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[11, 12, 13],
        [14, 15, 16]]])

In [5]:
a3.shape

(2, 2, 3)